name: Build WebGAL Terre For Intel Mac

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build-mac-intel:
    name: Build MacOS Binary
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: 'yarn'
      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: sh release-mac.sh
      - name: Compress
        run: 7z a -tzip release/WebGAL_Terre_Mac.zip release/*      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebGAL_Terre_Mac
          path: release/WebGAL_Terre_Mac.zip
