name: Release WebGAL Terre for Intel Mac

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*'

jobs:
  build-mac-intel:
    name: Build MacOS Binary
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'
      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: sh release-mac.sh
      - name: Compress
        run: 7z a -tzip WebGAL_Terre_Mac.zip release/*
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebGAL_Terre_Mac
          path: WebGAL_Terre_Mac.zip
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: ['build-mac-intel']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: WebGAL Terre ${{ github.ref }}
          body_path: releasenote.md
          draft: true
          prerelease: false

      - name: Upload MacOS Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: WebGAL_Terre_Mac/WebGAL_Terre_Mac.zip
          asset_name: WebGAL_Terre_Mac_${{ github.ref_name }}.zip
          asset_content_type: application/zip
